spring:
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://localhost:3306/training?
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #邮件发送配置
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    #    这里填发送验证的邮箱
    username: xxx@qq.com
    #    这里填写邮箱的授权码
    password: xxxxx
    #    配置邮箱456端口，否则本地测试可以，放到服务器上不行
    port: 465
    #这个端口有时候会出错，添加以下ssl配置。或者把端口改为 25
    properties:
      mail:
        debug: true #启动debug调试
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置
  servlet:
    multipart:
      #设置请求最大大小为20MB
      max-request-size: 2MB
      #设置文件上传最大大小为20MB
      max-file-size: 2MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.votesystem.domain
server:
  port: 7000
filePath:
  location: src/main/resources/static/headImg